# Generated by Django 5.1.6 on 2025-03-07 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_author_alter_blog_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
